name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 24.9.0
        uses: actions/setup-node@v4
        with:
          node-version: 24.9.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        env:
          CI: true
        run: npm test -- --watchAll=false

      - name: Build
        env:
          CI: true
        run: npm run build

  deploy:
    name: Deploy to Vercel (Deploy Hook)
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Vercel Deploy Hook
        env:
          DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$DEPLOY_HOOK_URL" ]; then
            echo "Missing VERCEL_DEPLOY_HOOK_URL secret" >&2
            exit 1
          fi
          echo "Triggering Vercel deploy hook..."
          curl --fail -X POST "$DEPLOY_HOOK_URL"

  deploy-preview:
    name: Deploy Preview to Vercel (Deploy Hook)
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Trigger Vercel Preview Deploy Hook
        env:
          PREVIEW_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_PREVIEW_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$PREVIEW_DEPLOY_HOOK_URL" ]; then
            echo "Missing VERCEL_PREVIEW_DEPLOY_HOOK_URL secret" >&2
            exit 1
          fi
          echo "Triggering Vercel preview deploy hook..."
          curl --fail -X POST "$PREVIEW_DEPLOY_HOOK_URL"
